/* *********************************************
Copyright (c) 2013-2024, Cornelis Jan (Jacco) van de Streek
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of my employers nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL CORNELIS JAN VAN DE STREEK BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
********************************************* */

#include "ReadCell.h"
#include "CrystalStructure.h"
#include "TestSuite.h"
#include "TextFileReader_2.h"

#include <cmath>
#include <iostream>


void test_ReadCell( TestSuite & test_suite )
{
    std::cout << "Now running tests for ReadCell." << std::endl;

    std::vector< std::string > contents;

    contents.push_back( "#*************************************************************************************" );
    contents.push_back( "#*                    Generated by cif2cell 1.2.7 2015-09-24 16:33                   *" );
    contents.push_back( "#*   T. Bjorkman, Comp. Phys. Commun. 182, 1183-1186 (2011). Please cite generously. *" );
    contents.push_back( "#*                                                                                   *" );
    contents.push_back( "#*                 Data obtained from CSD. Reference number : ADERIL                 *" );
    contents.push_back( "#*                      C8 H10 N2 O1   (" );
    contents.push_back( "" );
    contents.push_back( "#4-Methylbenzamidoxime)                     *" );
    contents.push_back( "#* Hai-Bo Wang et al., Acta Crystallogr.,Sect.E:Struct.Rep.Online  62, o3105- (2006) *" );
    contents.push_back( "#*************************************************************************************" );
    contents.push_back( "" );
    contents.push_back( "%BLOCK LATTICE_CART" );
    contents.push_back( "ang    # angstrom units" );
    contents.push_back( "   6.422000000000000   0.000000000000000   0.000000000000000" );
    contents.push_back( "   0.592746588633002   7.448451884899569   0.000000000000000" );
    contents.push_back( "   2.343612305591979   2.960298154818566  16.760992727033077" );
    contents.push_back( "%ENDBLOCK LATTICE_CART" );
    contents.push_back( "" );
    contents.push_back( "%BLOCK POSITIONS_FRAC" );
    contents.push_back( "O    0.762421500000000   0.481122300000000   0.497958800000000 " );
    contents.push_back( "O    0.237578500000000   0.518877700000000   0.502041200000000 " );
    contents.push_back( "O    0.742401200000000   0.486944000000000   0.997267200000000 " );
    contents.push_back( "O    0.257598800000000   0.513056000000000   0.002732800000000 " );
    contents.push_back( "N    0.588167700000000   0.569505000000000   0.368687300000000 " );
    contents.push_back( "N    0.411832300000000   0.430495000000000   0.631312700000000 " );
    contents.push_back( "N    0.892885100000000   0.562562900000000   0.429700000000000 " );
    contents.push_back( "N    0.107114900000000   0.437437100000000   0.570300000000000 " );
    contents.push_back( "N    0.609534500000000   0.426319500000000   0.068471300000000 " );
    contents.push_back( "N    0.390465500000000   0.573680500000000   0.931528700000000 " );
    contents.push_back( "N    0.925561500000000   0.298520800000000   0.113207700000000 " );
    contents.push_back( "N    0.074438500000000   0.701479200000000   0.886792300000000 " );
    contents.push_back( "C    0.289197600000000   0.925595000000000   0.072592400000000 " );
    contents.push_back( "C    0.710802400000000   0.074405000000000   0.927407600000000 " );
    contents.push_back( "C    0.158910300000000   0.842947400000000   0.147930800000000 " );
    contents.push_back( "C    0.841089700000000   0.157052600000000   0.852069200000000 " );
    contents.push_back( "C    0.220827400000000   0.847262000000000   0.222759300000000 " );
    contents.push_back( "C    0.779172600000000   0.152738000000000   0.777240700000000 " );
    contents.push_back( "C    0.101690400000000   0.771472500000000   0.293156400000000 " );
    contents.push_back( "C    0.898309600000000   0.228527500000000   0.706843600000000 " );
    contents.push_back( "C    0.915792700000000   0.686015400000000   0.291481300000000 " );
    contents.push_back( "C    0.084207300000000   0.313984600000000   0.708518700000000 " );
    contents.push_back( "C    0.852374700000000   0.682507600000000   0.216785800000000 " );
    contents.push_back( "C    0.147625300000000   0.317492400000000   0.783214200000000 " );
    contents.push_back( "C    0.971906400000000   0.759226900000000   0.146470300000000 " );
    contents.push_back( "C    0.028093600000000   0.240773100000000   0.853529700000000 " );
    contents.push_back( "C    0.793514700000000   0.601772300000000   0.366658600000000 " );
    contents.push_back( "C    0.206485300000000   0.398227700000000   0.633341400000000 " );
    contents.push_back( "C    0.242501300000000   0.092358900000000   0.435508600000000 " );
    contents.push_back( "C    0.757498700000000   0.907641100000000   0.564491400000000 " );
    contents.push_back( "C    0.362680200000000   0.152075300000000   0.354718000000000 " );
    contents.push_back( "C    0.637319800000000   0.847924700000000   0.645282000000000 " );
    contents.push_back( "C    0.272896400000000   0.279940600000000   0.296442800000000 " );
    contents.push_back( "C    0.727103600000000   0.720059400000000   0.703557200000000 " );
    contents.push_back( "C    0.385540100000000   0.340701100000000   0.222380600000000 " );
    contents.push_back( "C    0.614459900000000   0.659298900000000   0.777619400000000 " );
    contents.push_back( "C    0.592665100000000   0.271773000000000   0.203024700000000 " );
    contents.push_back( "C    0.407334900000000   0.728227000000000   0.796975300000000 " );
    contents.push_back( "C    0.682385600000000   0.142438900000000   0.260855900000000 " );
    contents.push_back( "C    0.317614400000000   0.857561100000000   0.739144100000000 " );
    contents.push_back( "C    0.569542400000000   0.084797000000000   0.335228500000000 " );
    contents.push_back( "C    0.430457600000000   0.915203000000000   0.664771500000000 " );
    contents.push_back( "C    0.714097400000000   0.336411200000000   0.124744900000000 " );
    contents.push_back( "C    0.285902600000000   0.663588800000000   0.875255100000000 " );
    contents.push_back( "H    0.869775500000000   0.451288000000000   0.537432200000000 " );
    contents.push_back( "H    0.130224500000000   0.548712000000000   0.462567800000000 " );
    contents.push_back( "H    0.422420100000000   0.993700300000000   0.085643800000000 " );
    contents.push_back( "H    0.577579900000000   0.006299700000000   0.914356200000000 " );
    contents.push_back( "H    0.195259200000000   0.026830900000000   0.034980000000000 " );
    contents.push_back( "H    0.804740800000000   0.973169100000000   0.965020000000000 " );
    contents.push_back( "H    0.351507600000000   0.820818300000000   0.036925000000000 " );
    contents.push_back( "H    0.648492400000000   0.179181700000000   0.963075000000000 " );
    contents.push_back( "H    0.509728700000000   0.502388500000000   0.419971700000000 " );
    contents.push_back( "H    0.490271300000000   0.497611500000000   0.580028300000000 " );
    contents.push_back( "H    0.521227500000000   0.582398700000000   0.317834900000000 " );
    contents.push_back( "H    0.478772500000000   0.417601300000000   0.682165100000000 " );
    contents.push_back( "H    0.364699500000000   0.912859300000000   0.225813300000000 " );
    contents.push_back( "H    0.635300500000000   0.087140700000000   0.774186700000000 " );
    contents.push_back( "H    0.151431400000000   0.780704700000000   0.350323600000000 " );
    contents.push_back( "H    0.848568600000000   0.219295300000000   0.649676400000000 " );
    contents.push_back( "H    0.709503500000000   0.617347200000000   0.212292700000000 " );
    contents.push_back( "H    0.290496500000000   0.382652800000000   0.787707300000000 " );
    contents.push_back( "H    0.919328200000000   0.751470300000000   0.089437500000000 " );
    contents.push_back( "H    0.080671800000000   0.248529700000000   0.910562500000000 " );
    contents.push_back( "H    0.631841200000000   0.533037200000000   0.960078900000000 " );
    contents.push_back( "H    0.368158800000000   0.466962800000000   0.039921100000000 " );
    contents.push_back( "H    0.008425600000000   0.366784800000000   0.063072900000000 " );
    contents.push_back( "H    0.991574400000000   0.633215200000000   0.936927100000000 " );
    contents.push_back( "H    0.003647100000000   0.263487400000000   0.161683400000000 " );
    contents.push_back( "H    0.996352900000000   0.736512600000000   0.838316600000000 " );
    contents.push_back( "H    0.078363000000000   0.146576000000000   0.438138200000000 " );
    contents.push_back( "H    0.921637000000000   0.853424000000000   0.561861800000000 " );
    contents.push_back( "H    0.312489900000000   0.142109300000000   0.481996500000000 " );
    contents.push_back( "H    0.687510100000000   0.857890700000000   0.518003500000000 " );
    contents.push_back( "H    0.244241900000000   0.942828400000000   0.451543200000000 " );
    contents.push_back( "H    0.755758100000000   0.057171600000000   0.548456800000000 " );
    contents.push_back( "H    0.112617600000000   0.335506200000000   0.310247200000000 " );
    contents.push_back( "H    0.887382400000000   0.664493800000000   0.689752800000000 " );
    contents.push_back( "H    0.313961100000000   0.445911000000000   0.179806300000000 " );
    contents.push_back( "H    0.686038900000000   0.554089000000000   0.820193700000000 " );
    contents.push_back( "H    0.840983000000000   0.082585000000000   0.248090000000000 " );
    contents.push_back( "H    0.159017000000000   0.917415000000000   0.751910000000000 " );
    contents.push_back( "H    0.644206900000000   0.984083300000000   0.378751500000000 " );
    contents.push_back( "H    0.355793100000000   0.015916700000000   0.621248500000000 " );
    contents.push_back( "%ENDBLOCK POSITIONS_FRAC" );
    contents.push_back( "" );
    contents.push_back( "# Commented out pseudopotential block for easy editing" );
    contents.push_back( "#%BLOCK SPECIES_POT" );
    contents.push_back( "# H   H_00.usp" );
    contents.push_back( "# C   C_00.usp" );
    contents.push_back( "# O   O_00.usp" );
    contents.push_back( "# N   N_00.usp" );
    contents.push_back( "#%ENDBLOCK SPECIES_POT" );
    contents.push_back( "" );
    contents.push_back( "%BLOCK SYMMETRY_OPS" );
    contents.push_back( "# Symm. op. 1" );
    contents.push_back( "  1.000000000000000   0.000000000000000   0.000000000000000 " );
    contents.push_back( " -0.000000000000000   1.000000000000000   0.000000000000000 " );
    contents.push_back( "  0.000000000000000   0.000000000000000   1.000000000000000 " );
    contents.push_back( "  0.000000000000000   0.000000000000000   0.000000000000000 " );
    contents.push_back( "# Symm. op. 2" );
    contents.push_back( " -1.000000000000000   0.000000000000000   0.000000000000000 " );
    contents.push_back( "  0.000000000000000  -1.000000000000000   0.000000000000000 " );
    contents.push_back( "  0.000000000000000   0.000000000000000  -1.000000000000000 " );
    contents.push_back( "  0.000000000000000   0.000000000000000   0.000000000000000 " );
    contents.push_back( "%ENDBLOCK SYMMETRY_OPS" );
    contents.push_back( "" );
    contents.push_back( "KPOINTS_MP_SPACING : 0.05" );
    contents.push_back( "KPOINTS_MP_OFFSET : 0.25 0.25 0.25" );
    contents.push_back( "FIX_ALL_CELL : false" );
    contents.push_back( "FIX_COM : true" );
    contents.push_back( "FIX_ALL_IONS : false" );
    contents.push_back( "" );
    contents.push_back( "%BLOCK IONIC_CONSTRAINTS" );
    contents.push_back( "%ENDBLOCK IONIC_CONSTRAINTS" );
    TextFileReader_2 tfr( contents );
    CrystalStructure crystal_structure;
    read_cell( tfr, crystal_structure );
    
}

